FORMAT: 1A
HOST: https://api.example.test

# Example Tasks API
A resource action is – in fact – a state transition. This API example
demonstrates an action - state transition - to another resource.


# Group Tasks

## Collection [/tasks{?status,priority}]

+ Parameters
    + status (string, optional)
    + priority (number, optional)

### List All Tasks [GET]

+ Response 200 (application/json)

        [
            {
                "id": 123,
                "name": "Exercise in gym",
                "done": false,
                "type": "task"
            },
            {
                "id": 124,
                "name": "Shop for groceries",
                "done": true,
                "type": "task"
            }
        ]

## Resource [/tasks/{id}]

### Retrieve Task [GET]
This is a state transition to another resource.

+ Parameters
    + id (string)

+ Response 200 (application/json)

        {
            "id": 123,
            "name": "Go to gym",
            "done": false,
            "type": "task"
        }

### Delete Task [DELETE]

+ Parameters
    + id (string)

+ Response 204
